// **********************************************************************
//
// Copyright (c) 2003-2011 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.4.2
//
// <auto-generated>
//
// Generated from file `common_types.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

#ifndef __C__Enisey_src_EniseySolution_Enisey_common_types_h__
#define __C__Enisey_src_EniseySolution_Enisey_common_types_h__

#include <Ice/LocalObjectF.h>
#include <Ice/ProxyF.h>
#include <Ice/ObjectF.h>
#include <Ice/Exception.h>
#include <Ice/LocalObject.h>
#include <IceUtil/ScopedArray.h>
#include <Ice/UndefSysMacros.h>

#ifndef ICE_IGNORE_VERSION
#   if ICE_INT_VERSION / 100 != 304
#       error Ice version mismatch!
#   endif
#   if ICE_INT_VERSION % 100 > 50
#       error Beta header file detected
#   endif
#   if ICE_INT_VERSION % 100 < 2
#       error Ice patch level mismatch!
#   endif
#endif

namespace Enisey
{

typedef ::std::vector< ::Ice::Double> DoubleSequence;

typedef ::std::vector< ::Ice::Int> IntSequence;

typedef ::std::vector< ::std::string> StringSequence;

}

#endif
