// **********************************************************************
//
// Copyright (c) 2003-2011 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.4.2
//
// <auto-generated>
//
// Generated from file `gas_transfer_system_ice.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

#include <gas_transfer_system_ice.h>
#include <Ice/LocalException.h>
#include <Ice/ObjectFactory.h>
#include <Ice/BasicStream.h>
#include <IceUtil/Iterator.h>

#ifndef ICE_IGNORE_VERSION
#   if ICE_INT_VERSION / 100 != 304
#       error Ice version mismatch!
#   endif
#   if ICE_INT_VERSION % 100 > 50
#       error Beta header file detected
#   endif
#   if ICE_INT_VERSION % 100 < 2
#       error Ice patch level mismatch!
#   endif
#endif

static const ::std::string __Enisey__GasTransferSystemIce__PerformBalancing_name = "PerformBalancing";

::Ice::Object* IceInternal::upCast(::Enisey::GasTransferSystemIce* p) { return p; }
::IceProxy::Ice::Object* IceInternal::upCast(::IceProxy::Enisey::GasTransferSystemIce* p) { return p; }

void
Enisey::__read(::IceInternal::BasicStream* __is, ::Enisey::GasTransferSystemIcePrx& v)
{
    ::Ice::ObjectPrx proxy;
    __is->read(proxy);
    if(!proxy)
    {
        v = 0;
    }
    else
    {
        v = new ::IceProxy::Enisey::GasTransferSystemIce;
        v->__copyFrom(proxy);
    }
}

void
IceProxy::Enisey::GasTransferSystemIce::PerformBalancing(::Ice::Int NumberOfIterations, const ::Enisey::StringSequence& MatrixConnectionsFile, const ::Enisey::StringSequence& InOutGRSFile, const ::Enisey::StringSequence& PipeLinesFile, ::Enisey::StringSequence& ResultFile, ::Enisey::DoubleSequence& AbsDisbalances, ::Enisey::IntSequence& IntDisbalances, const ::Ice::Context* __ctx)
{
    int __cnt = 0;
    while(true)
    {
        ::IceInternal::Handle< ::IceDelegate::Ice::Object> __delBase;
        try
        {
            __checkTwowayOnly(__Enisey__GasTransferSystemIce__PerformBalancing_name);
            __delBase = __getDelegate(false);
            ::IceDelegate::Enisey::GasTransferSystemIce* __del = dynamic_cast< ::IceDelegate::Enisey::GasTransferSystemIce*>(__delBase.get());
            __del->PerformBalancing(NumberOfIterations, MatrixConnectionsFile, InOutGRSFile, PipeLinesFile, ResultFile, AbsDisbalances, IntDisbalances, __ctx);
            return;
        }
        catch(const ::IceInternal::LocalExceptionWrapper& __ex)
        {
            __handleExceptionWrapperRelaxed(__delBase, __ex, true, __cnt);
        }
        catch(const ::Ice::LocalException& __ex)
        {
            __handleException(__delBase, __ex, true, __cnt);
        }
    }
}

::Ice::AsyncResultPtr
IceProxy::Enisey::GasTransferSystemIce::begin_PerformBalancing(::Ice::Int NumberOfIterations, const ::Enisey::StringSequence& MatrixConnectionsFile, const ::Enisey::StringSequence& InOutGRSFile, const ::Enisey::StringSequence& PipeLinesFile, const ::Ice::Context* __ctx, const ::IceInternal::CallbackBasePtr& __del, const ::Ice::LocalObjectPtr& __cookie)
{
    __checkAsyncTwowayOnly(__Enisey__GasTransferSystemIce__PerformBalancing_name);
    ::IceInternal::OutgoingAsyncPtr __result = new ::IceInternal::OutgoingAsync(this, __Enisey__GasTransferSystemIce__PerformBalancing_name, __del, __cookie);
    try
    {
        __result->__prepare(__Enisey__GasTransferSystemIce__PerformBalancing_name, ::Ice::Idempotent, __ctx);
        ::IceInternal::BasicStream* __os = __result->__getOs();
        __os->write(NumberOfIterations);
        if(MatrixConnectionsFile.size() == 0)
        {
            __os->writeSize(0);
        }
        else
        {
            __os->write(&MatrixConnectionsFile[0], &MatrixConnectionsFile[0] + MatrixConnectionsFile.size());
        }
        if(InOutGRSFile.size() == 0)
        {
            __os->writeSize(0);
        }
        else
        {
            __os->write(&InOutGRSFile[0], &InOutGRSFile[0] + InOutGRSFile.size());
        }
        if(PipeLinesFile.size() == 0)
        {
            __os->writeSize(0);
        }
        else
        {
            __os->write(&PipeLinesFile[0], &PipeLinesFile[0] + PipeLinesFile.size());
        }
        __os->endWriteEncaps();
        __result->__send(true);
    }
    catch(const ::Ice::LocalException& __ex)
    {
        __result->__exceptionAsync(__ex);
    }
    return __result;
}

void
IceProxy::Enisey::GasTransferSystemIce::end_PerformBalancing(::Enisey::StringSequence& ResultFile, ::Enisey::DoubleSequence& AbsDisbalances, ::Enisey::IntSequence& IntDisbalances, const ::Ice::AsyncResultPtr& __result)
{
    ::Ice::AsyncResult::__check(__result, this, __Enisey__GasTransferSystemIce__PerformBalancing_name);
    if(!__result->__wait())
    {
        try
        {
            __result->__throwUserException();
        }
        catch(const ::Ice::UserException& __ex)
        {
            throw ::Ice::UnknownUserException(__FILE__, __LINE__, __ex.ice_name());
        }
    }
    ::IceInternal::BasicStream* __is = __result->__getIs();
    __is->startReadEncaps();
    __is->read(ResultFile);
    __is->read(AbsDisbalances);
    __is->read(IntDisbalances);
    __is->endReadEncaps();
}

const ::std::string&
IceProxy::Enisey::GasTransferSystemIce::ice_staticId()
{
    return ::Enisey::GasTransferSystemIce::ice_staticId();
}

::IceInternal::Handle< ::IceDelegateM::Ice::Object>
IceProxy::Enisey::GasTransferSystemIce::__createDelegateM()
{
    return ::IceInternal::Handle< ::IceDelegateM::Ice::Object>(new ::IceDelegateM::Enisey::GasTransferSystemIce);
}

::IceInternal::Handle< ::IceDelegateD::Ice::Object>
IceProxy::Enisey::GasTransferSystemIce::__createDelegateD()
{
    return ::IceInternal::Handle< ::IceDelegateD::Ice::Object>(new ::IceDelegateD::Enisey::GasTransferSystemIce);
}

::IceProxy::Ice::Object*
IceProxy::Enisey::GasTransferSystemIce::__newInstance() const
{
    return new GasTransferSystemIce;
}

void
IceDelegateM::Enisey::GasTransferSystemIce::PerformBalancing(::Ice::Int NumberOfIterations, const ::Enisey::StringSequence& MatrixConnectionsFile, const ::Enisey::StringSequence& InOutGRSFile, const ::Enisey::StringSequence& PipeLinesFile, ::Enisey::StringSequence& ResultFile, ::Enisey::DoubleSequence& AbsDisbalances, ::Enisey::IntSequence& IntDisbalances, const ::Ice::Context* __context)
{
    ::IceInternal::Outgoing __og(__handler.get(), __Enisey__GasTransferSystemIce__PerformBalancing_name, ::Ice::Idempotent, __context);
    try
    {
        ::IceInternal::BasicStream* __os = __og.os();
        __os->write(NumberOfIterations);
        if(MatrixConnectionsFile.size() == 0)
        {
            __os->writeSize(0);
        }
        else
        {
            __os->write(&MatrixConnectionsFile[0], &MatrixConnectionsFile[0] + MatrixConnectionsFile.size());
        }
        if(InOutGRSFile.size() == 0)
        {
            __os->writeSize(0);
        }
        else
        {
            __os->write(&InOutGRSFile[0], &InOutGRSFile[0] + InOutGRSFile.size());
        }
        if(PipeLinesFile.size() == 0)
        {
            __os->writeSize(0);
        }
        else
        {
            __os->write(&PipeLinesFile[0], &PipeLinesFile[0] + PipeLinesFile.size());
        }
    }
    catch(const ::Ice::LocalException& __ex)
    {
        __og.abort(__ex);
    }
    bool __ok = __og.invoke();
    try
    {
        if(!__ok)
        {
            try
            {
                __og.throwUserException();
            }
            catch(const ::Ice::UserException& __ex)
            {
                ::Ice::UnknownUserException __uue(__FILE__, __LINE__, __ex.ice_name());
                throw __uue;
            }
        }
        ::IceInternal::BasicStream* __is = __og.is();
        __is->startReadEncaps();
        __is->read(ResultFile);
        __is->read(AbsDisbalances);
        __is->read(IntDisbalances);
        __is->endReadEncaps();
    }
    catch(const ::Ice::LocalException& __ex)
    {
        throw ::IceInternal::LocalExceptionWrapper(__ex, false);
    }
}

void
IceDelegateD::Enisey::GasTransferSystemIce::PerformBalancing(::Ice::Int NumberOfIterations, const ::Enisey::StringSequence& MatrixConnectionsFile, const ::Enisey::StringSequence& InOutGRSFile, const ::Enisey::StringSequence& PipeLinesFile, ::Enisey::StringSequence& ResultFile, ::Enisey::DoubleSequence& AbsDisbalances, ::Enisey::IntSequence& IntDisbalances, const ::Ice::Context* __context)
{
    class _DirectI : public ::IceInternal::Direct
    {
    public:

        _DirectI(::Ice::Int NumberOfIterations, const ::Enisey::StringSequence& MatrixConnectionsFile, const ::Enisey::StringSequence& InOutGRSFile, const ::Enisey::StringSequence& PipeLinesFile, ::Enisey::StringSequence& ResultFile, ::Enisey::DoubleSequence& AbsDisbalances, ::Enisey::IntSequence& IntDisbalances, const ::Ice::Current& __current) : 
            ::IceInternal::Direct(__current),
            _m_NumberOfIterations(NumberOfIterations),
            _m_MatrixConnectionsFile(MatrixConnectionsFile),
            _m_InOutGRSFile(InOutGRSFile),
            _m_PipeLinesFile(PipeLinesFile),
            _m_ResultFile(ResultFile),
            _m_AbsDisbalances(AbsDisbalances),
            _m_IntDisbalances(IntDisbalances)
        {
        }
        
        virtual ::Ice::DispatchStatus
        run(::Ice::Object* object)
        {
            ::Enisey::GasTransferSystemIce* servant = dynamic_cast< ::Enisey::GasTransferSystemIce*>(object);
            if(!servant)
            {
                throw ::Ice::OperationNotExistException(__FILE__, __LINE__, _current.id, _current.facet, _current.operation);
            }
            servant->PerformBalancing(_m_NumberOfIterations, _m_MatrixConnectionsFile, _m_InOutGRSFile, _m_PipeLinesFile, _m_ResultFile, _m_AbsDisbalances, _m_IntDisbalances, _current);
            return ::Ice::DispatchOK;
        }
        
    private:
        
        ::Ice::Int _m_NumberOfIterations;
        const ::Enisey::StringSequence& _m_MatrixConnectionsFile;
        const ::Enisey::StringSequence& _m_InOutGRSFile;
        const ::Enisey::StringSequence& _m_PipeLinesFile;
        ::Enisey::StringSequence& _m_ResultFile;
        ::Enisey::DoubleSequence& _m_AbsDisbalances;
        ::Enisey::IntSequence& _m_IntDisbalances;
    };
    
    ::Ice::Current __current;
    __initCurrent(__current, __Enisey__GasTransferSystemIce__PerformBalancing_name, ::Ice::Idempotent, __context);
    try
    {
        _DirectI __direct(NumberOfIterations, MatrixConnectionsFile, InOutGRSFile, PipeLinesFile, ResultFile, AbsDisbalances, IntDisbalances, __current);
        try
        {
            __direct.servant()->__collocDispatch(__direct);
        }
        catch(...)
        {
            __direct.destroy();
            throw;
        }
        __direct.destroy();
    }
    catch(const ::Ice::SystemException&)
    {
        throw;
    }
    catch(const ::IceInternal::LocalExceptionWrapper&)
    {
        throw;
    }
    catch(const ::std::exception& __ex)
    {
        ::IceInternal::LocalExceptionWrapper::throwWrapper(__ex);
    }
    catch(...)
    {
        throw ::IceInternal::LocalExceptionWrapper(::Ice::UnknownException(__FILE__, __LINE__, "unknown c++ exception"), false);
    }
}

::Ice::ObjectPtr
Enisey::GasTransferSystemIce::ice_clone() const
{
    throw ::Ice::CloneNotImplementedException(__FILE__, __LINE__);
    return 0; // to avoid a warning with some compilers
}

static const ::std::string __Enisey__GasTransferSystemIce_ids[2] =
{
    "::Enisey::GasTransferSystemIce",
    "::Ice::Object"
};

bool
Enisey::GasTransferSystemIce::ice_isA(const ::std::string& _s, const ::Ice::Current&) const
{
    return ::std::binary_search(__Enisey__GasTransferSystemIce_ids, __Enisey__GasTransferSystemIce_ids + 2, _s);
}

::std::vector< ::std::string>
Enisey::GasTransferSystemIce::ice_ids(const ::Ice::Current&) const
{
    return ::std::vector< ::std::string>(&__Enisey__GasTransferSystemIce_ids[0], &__Enisey__GasTransferSystemIce_ids[2]);
}

const ::std::string&
Enisey::GasTransferSystemIce::ice_id(const ::Ice::Current&) const
{
    return __Enisey__GasTransferSystemIce_ids[0];
}

const ::std::string&
Enisey::GasTransferSystemIce::ice_staticId()
{
    return __Enisey__GasTransferSystemIce_ids[0];
}

::Ice::DispatchStatus
Enisey::GasTransferSystemIce::___PerformBalancing(::IceInternal::Incoming& __inS, const ::Ice::Current& __current)
{
    __checkMode(::Ice::Idempotent, __current.mode);
    ::IceInternal::BasicStream* __is = __inS.is();
    __is->startReadEncaps();
    ::Ice::Int NumberOfIterations;
    ::Enisey::StringSequence MatrixConnectionsFile;
    ::Enisey::StringSequence InOutGRSFile;
    ::Enisey::StringSequence PipeLinesFile;
    __is->read(NumberOfIterations);
    __is->read(MatrixConnectionsFile);
    __is->read(InOutGRSFile);
    __is->read(PipeLinesFile);
    __is->endReadEncaps();
    ::IceInternal::BasicStream* __os = __inS.os();
    ::Enisey::StringSequence ResultFile;
    ::Enisey::DoubleSequence AbsDisbalances;
    ::Enisey::IntSequence IntDisbalances;
    PerformBalancing(NumberOfIterations, MatrixConnectionsFile, InOutGRSFile, PipeLinesFile, ResultFile, AbsDisbalances, IntDisbalances, __current);
    if(ResultFile.size() == 0)
    {
        __os->writeSize(0);
    }
    else
    {
        __os->write(&ResultFile[0], &ResultFile[0] + ResultFile.size());
    }
    if(AbsDisbalances.size() == 0)
    {
        __os->writeSize(0);
    }
    else
    {
        __os->write(&AbsDisbalances[0], &AbsDisbalances[0] + AbsDisbalances.size());
    }
    if(IntDisbalances.size() == 0)
    {
        __os->writeSize(0);
    }
    else
    {
        __os->write(&IntDisbalances[0], &IntDisbalances[0] + IntDisbalances.size());
    }
    return ::Ice::DispatchOK;
}

static ::std::string __Enisey__GasTransferSystemIce_all[] =
{
    "PerformBalancing",
    "ice_id",
    "ice_ids",
    "ice_isA",
    "ice_ping"
};

::Ice::DispatchStatus
Enisey::GasTransferSystemIce::__dispatch(::IceInternal::Incoming& in, const ::Ice::Current& current)
{
    ::std::pair< ::std::string*, ::std::string*> r = ::std::equal_range(__Enisey__GasTransferSystemIce_all, __Enisey__GasTransferSystemIce_all + 5, current.operation);
    if(r.first == r.second)
    {
        throw ::Ice::OperationNotExistException(__FILE__, __LINE__, current.id, current.facet, current.operation);
    }

    switch(r.first - __Enisey__GasTransferSystemIce_all)
    {
        case 0:
        {
            return ___PerformBalancing(in, current);
        }
        case 1:
        {
            return ___ice_id(in, current);
        }
        case 2:
        {
            return ___ice_ids(in, current);
        }
        case 3:
        {
            return ___ice_isA(in, current);
        }
        case 4:
        {
            return ___ice_ping(in, current);
        }
    }

    assert(false);
    throw ::Ice::OperationNotExistException(__FILE__, __LINE__, current.id, current.facet, current.operation);
}

void
Enisey::GasTransferSystemIce::__write(::IceInternal::BasicStream* __os) const
{
    __os->writeTypeId(ice_staticId());
    __os->startWriteSlice();
    __os->endWriteSlice();
#if defined(_MSC_VER) && (_MSC_VER < 1300) // VC++ 6 compiler bug
    Object::__write(__os);
#else
    ::Ice::Object::__write(__os);
#endif
}

void
Enisey::GasTransferSystemIce::__read(::IceInternal::BasicStream* __is, bool __rid)
{
    if(__rid)
    {
        ::std::string myId;
        __is->readTypeId(myId);
    }
    __is->startReadSlice();
    __is->endReadSlice();
#if defined(_MSC_VER) && (_MSC_VER < 1300) // VC++ 6 compiler bug
    Object::__read(__is, true);
#else
    ::Ice::Object::__read(__is, true);
#endif
}

// COMPILERFIX: Stream API is not supported with VC++ 6
#if !defined(_MSC_VER) || (_MSC_VER >= 1300)
void
Enisey::GasTransferSystemIce::__write(const ::Ice::OutputStreamPtr&) const
{
    Ice::MarshalException ex(__FILE__, __LINE__);
    ex.reason = "type Enisey::GasTransferSystemIce was not generated with stream support";
    throw ex;
}

void
Enisey::GasTransferSystemIce::__read(const ::Ice::InputStreamPtr&, bool)
{
    Ice::MarshalException ex(__FILE__, __LINE__);
    ex.reason = "type Enisey::GasTransferSystemIce was not generated with stream support";
    throw ex;
}
#endif

void 
Enisey::__patch__GasTransferSystemIcePtr(void* __addr, ::Ice::ObjectPtr& v)
{
    ::Enisey::GasTransferSystemIcePtr* p = static_cast< ::Enisey::GasTransferSystemIcePtr*>(__addr);
    assert(p);
    *p = ::Enisey::GasTransferSystemIcePtr::dynamicCast(v);
    if(v && !*p)
    {
        IceInternal::Ex::throwUOE(::Enisey::GasTransferSystemIce::ice_staticId(), v->ice_id());
    }
}
