// **********************************************************************
//
// Copyright (c) 2003-2011 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.4.2
//
// <auto-generated>
//
// Generated from file `slae_solver_ice.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

#ifndef __C__Enisey_src_EniseySolution_Enisey_slae_solver_ice_h__
#define __C__Enisey_src_EniseySolution_Enisey_slae_solver_ice_h__

#include <Ice/LocalObjectF.h>
#include <Ice/ProxyF.h>
#include <Ice/ObjectF.h>
#include <Ice/Exception.h>
#include <Ice/LocalObject.h>
#include <Ice/Proxy.h>
#include <Ice/Object.h>
#include <Ice/Outgoing.h>
#include <Ice/OutgoingAsync.h>
#include <Ice/Incoming.h>
#include <Ice/Direct.h>
#include <IceUtil/ScopedArray.h>
#include <Ice/StreamF.h>
#include <C:/Enisey/src/EniseySolution/ice_server/common_types.h>
#include <Ice/UndefSysMacros.h>

#ifndef ICE_IGNORE_VERSION
#   if ICE_INT_VERSION / 100 != 304
#       error Ice version mismatch!
#   endif
#   if ICE_INT_VERSION % 100 > 50
#       error Beta header file detected
#   endif
#   if ICE_INT_VERSION % 100 < 2
#       error Ice patch level mismatch!
#   endif
#endif

namespace IceProxy
{

namespace Enisey
{

class SlaeSolverIce;

}

}

namespace Enisey
{

class SlaeSolverIce;
bool operator==(const SlaeSolverIce&, const SlaeSolverIce&);
bool operator<(const SlaeSolverIce&, const SlaeSolverIce&);

}

namespace IceInternal
{

::Ice::Object* upCast(::Enisey::SlaeSolverIce*);
::IceProxy::Ice::Object* upCast(::IceProxy::Enisey::SlaeSolverIce*);

}

namespace Enisey
{

typedef ::IceInternal::Handle< ::Enisey::SlaeSolverIce> SlaeSolverIcePtr;
typedef ::IceInternal::ProxyHandle< ::IceProxy::Enisey::SlaeSolverIce> SlaeSolverIcePrx;

void __read(::IceInternal::BasicStream*, SlaeSolverIcePrx&);
void __patch__SlaeSolverIcePtr(void*, ::Ice::ObjectPtr&);

}

namespace Enisey
{

class Callback_SlaeSolverIce_Solve_Base : virtual public ::IceInternal::CallbackBase { };
typedef ::IceUtil::Handle< Callback_SlaeSolverIce_Solve_Base> Callback_SlaeSolverIce_SolvePtr;

}

namespace IceProxy
{

namespace Enisey
{

class SlaeSolverIce : virtual public ::IceProxy::Ice::Object
{
public:

    void Solve(const ::Enisey::IntSequence& AIndexes, const ::Enisey::DoubleSequence& AValues, const ::Enisey::DoubleSequence& B, ::Enisey::DoubleSequence& X)
    {
        Solve(AIndexes, AValues, B, X, 0);
    }
    void Solve(const ::Enisey::IntSequence& AIndexes, const ::Enisey::DoubleSequence& AValues, const ::Enisey::DoubleSequence& B, ::Enisey::DoubleSequence& X, const ::Ice::Context& __ctx)
    {
        Solve(AIndexes, AValues, B, X, &__ctx);
    }

    ::Ice::AsyncResultPtr begin_Solve(const ::Enisey::IntSequence& AIndexes, const ::Enisey::DoubleSequence& AValues, const ::Enisey::DoubleSequence& B)
    {
        return begin_Solve(AIndexes, AValues, B, 0, ::IceInternal::__dummyCallback, 0);
    }

    ::Ice::AsyncResultPtr begin_Solve(const ::Enisey::IntSequence& AIndexes, const ::Enisey::DoubleSequence& AValues, const ::Enisey::DoubleSequence& B, const ::Ice::Context& __ctx)
    {
        return begin_Solve(AIndexes, AValues, B, &__ctx, ::IceInternal::__dummyCallback, 0);
    }

    ::Ice::AsyncResultPtr begin_Solve(const ::Enisey::IntSequence& AIndexes, const ::Enisey::DoubleSequence& AValues, const ::Enisey::DoubleSequence& B, const ::Ice::CallbackPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_Solve(AIndexes, AValues, B, 0, __del, __cookie);
    }

    ::Ice::AsyncResultPtr begin_Solve(const ::Enisey::IntSequence& AIndexes, const ::Enisey::DoubleSequence& AValues, const ::Enisey::DoubleSequence& B, const ::Ice::Context& __ctx, const ::Ice::CallbackPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_Solve(AIndexes, AValues, B, &__ctx, __del, __cookie);
    }

    ::Ice::AsyncResultPtr begin_Solve(const ::Enisey::IntSequence& AIndexes, const ::Enisey::DoubleSequence& AValues, const ::Enisey::DoubleSequence& B, const ::Enisey::Callback_SlaeSolverIce_SolvePtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_Solve(AIndexes, AValues, B, 0, __del, __cookie);
    }

    ::Ice::AsyncResultPtr begin_Solve(const ::Enisey::IntSequence& AIndexes, const ::Enisey::DoubleSequence& AValues, const ::Enisey::DoubleSequence& B, const ::Ice::Context& __ctx, const ::Enisey::Callback_SlaeSolverIce_SolvePtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_Solve(AIndexes, AValues, B, &__ctx, __del, __cookie);
    }

    void end_Solve(::Enisey::DoubleSequence& X, const ::Ice::AsyncResultPtr&);
    
private:

    void Solve(const ::Enisey::IntSequence&, const ::Enisey::DoubleSequence&, const ::Enisey::DoubleSequence&, ::Enisey::DoubleSequence&, const ::Ice::Context*);
    ::Ice::AsyncResultPtr begin_Solve(const ::Enisey::IntSequence&, const ::Enisey::DoubleSequence&, const ::Enisey::DoubleSequence&, const ::Ice::Context*, const ::IceInternal::CallbackBasePtr&, const ::Ice::LocalObjectPtr& __cookie = 0);
    
public:
    
    ::IceInternal::ProxyHandle<SlaeSolverIce> ice_context(const ::Ice::Context& __context) const
    {
    #if defined(_MSC_VER) && (_MSC_VER < 1300) // VC++ 6 compiler bug
        typedef ::IceProxy::Ice::Object _Base;
        return dynamic_cast<SlaeSolverIce*>(_Base::ice_context(__context).get());
    #else
        return dynamic_cast<SlaeSolverIce*>(::IceProxy::Ice::Object::ice_context(__context).get());
    #endif
    }
    
    ::IceInternal::ProxyHandle<SlaeSolverIce> ice_adapterId(const std::string& __id) const
    {
    #if defined(_MSC_VER) && (_MSC_VER < 1300) // VC++ 6 compiler bug
        typedef ::IceProxy::Ice::Object _Base;
        return dynamic_cast<SlaeSolverIce*>(_Base::ice_adapterId(__id).get());
    #else
        return dynamic_cast<SlaeSolverIce*>(::IceProxy::Ice::Object::ice_adapterId(__id).get());
    #endif
    }
    
    ::IceInternal::ProxyHandle<SlaeSolverIce> ice_endpoints(const ::Ice::EndpointSeq& __endpoints) const
    {
    #if defined(_MSC_VER) && (_MSC_VER < 1300) // VC++ 6 compiler bug
        typedef ::IceProxy::Ice::Object _Base;
        return dynamic_cast<SlaeSolverIce*>(_Base::ice_endpoints(__endpoints).get());
    #else
        return dynamic_cast<SlaeSolverIce*>(::IceProxy::Ice::Object::ice_endpoints(__endpoints).get());
    #endif
    }
    
    ::IceInternal::ProxyHandle<SlaeSolverIce> ice_locatorCacheTimeout(int __timeout) const
    {
    #if defined(_MSC_VER) && (_MSC_VER < 1300) // VC++ 6 compiler bug
        typedef ::IceProxy::Ice::Object _Base;
        return dynamic_cast<SlaeSolverIce*>(_Base::ice_locatorCacheTimeout(__timeout).get());
    #else
        return dynamic_cast<SlaeSolverIce*>(::IceProxy::Ice::Object::ice_locatorCacheTimeout(__timeout).get());
    #endif
    }
    
    ::IceInternal::ProxyHandle<SlaeSolverIce> ice_connectionCached(bool __cached) const
    {
    #if defined(_MSC_VER) && (_MSC_VER < 1300) // VC++ 6 compiler bug
        typedef ::IceProxy::Ice::Object _Base;
        return dynamic_cast<SlaeSolverIce*>(_Base::ice_connectionCached(__cached).get());
    #else
        return dynamic_cast<SlaeSolverIce*>(::IceProxy::Ice::Object::ice_connectionCached(__cached).get());
    #endif
    }
    
    ::IceInternal::ProxyHandle<SlaeSolverIce> ice_endpointSelection(::Ice::EndpointSelectionType __est) const
    {
    #if defined(_MSC_VER) && (_MSC_VER < 1300) // VC++ 6 compiler bug
        typedef ::IceProxy::Ice::Object _Base;
        return dynamic_cast<SlaeSolverIce*>(_Base::ice_endpointSelection(__est).get());
    #else
        return dynamic_cast<SlaeSolverIce*>(::IceProxy::Ice::Object::ice_endpointSelection(__est).get());
    #endif
    }
    
    ::IceInternal::ProxyHandle<SlaeSolverIce> ice_secure(bool __secure) const
    {
    #if defined(_MSC_VER) && (_MSC_VER < 1300) // VC++ 6 compiler bug
        typedef ::IceProxy::Ice::Object _Base;
        return dynamic_cast<SlaeSolverIce*>(_Base::ice_secure(__secure).get());
    #else
        return dynamic_cast<SlaeSolverIce*>(::IceProxy::Ice::Object::ice_secure(__secure).get());
    #endif
    }
    
    ::IceInternal::ProxyHandle<SlaeSolverIce> ice_preferSecure(bool __preferSecure) const
    {
    #if defined(_MSC_VER) && (_MSC_VER < 1300) // VC++ 6 compiler bug
        typedef ::IceProxy::Ice::Object _Base;
        return dynamic_cast<SlaeSolverIce*>(_Base::ice_preferSecure(__preferSecure).get());
    #else
        return dynamic_cast<SlaeSolverIce*>(::IceProxy::Ice::Object::ice_preferSecure(__preferSecure).get());
    #endif
    }
    
    ::IceInternal::ProxyHandle<SlaeSolverIce> ice_router(const ::Ice::RouterPrx& __router) const
    {
    #if defined(_MSC_VER) && (_MSC_VER < 1300) // VC++ 6 compiler bug
        typedef ::IceProxy::Ice::Object _Base;
        return dynamic_cast<SlaeSolverIce*>(_Base::ice_router(__router).get());
    #else
        return dynamic_cast<SlaeSolverIce*>(::IceProxy::Ice::Object::ice_router(__router).get());
    #endif
    }
    
    ::IceInternal::ProxyHandle<SlaeSolverIce> ice_locator(const ::Ice::LocatorPrx& __locator) const
    {
    #if defined(_MSC_VER) && (_MSC_VER < 1300) // VC++ 6 compiler bug
        typedef ::IceProxy::Ice::Object _Base;
        return dynamic_cast<SlaeSolverIce*>(_Base::ice_locator(__locator).get());
    #else
        return dynamic_cast<SlaeSolverIce*>(::IceProxy::Ice::Object::ice_locator(__locator).get());
    #endif
    }
    
    ::IceInternal::ProxyHandle<SlaeSolverIce> ice_collocationOptimized(bool __co) const
    {
    #if defined(_MSC_VER) && (_MSC_VER < 1300) // VC++ 6 compiler bug
        typedef ::IceProxy::Ice::Object _Base;
        return dynamic_cast<SlaeSolverIce*>(_Base::ice_collocationOptimized(__co).get());
    #else
        return dynamic_cast<SlaeSolverIce*>(::IceProxy::Ice::Object::ice_collocationOptimized(__co).get());
    #endif
    }
    
    ::IceInternal::ProxyHandle<SlaeSolverIce> ice_twoway() const
    {
    #if defined(_MSC_VER) && (_MSC_VER < 1300) // VC++ 6 compiler bug
        typedef ::IceProxy::Ice::Object _Base;
        return dynamic_cast<SlaeSolverIce*>(_Base::ice_twoway().get());
    #else
        return dynamic_cast<SlaeSolverIce*>(::IceProxy::Ice::Object::ice_twoway().get());
    #endif
    }
    
    ::IceInternal::ProxyHandle<SlaeSolverIce> ice_oneway() const
    {
    #if defined(_MSC_VER) && (_MSC_VER < 1300) // VC++ 6 compiler bug
        typedef ::IceProxy::Ice::Object _Base;
        return dynamic_cast<SlaeSolverIce*>(_Base::ice_oneway().get());
    #else
        return dynamic_cast<SlaeSolverIce*>(::IceProxy::Ice::Object::ice_oneway().get());
    #endif
    }
    
    ::IceInternal::ProxyHandle<SlaeSolverIce> ice_batchOneway() const
    {
    #if defined(_MSC_VER) && (_MSC_VER < 1300) // VC++ 6 compiler bug
        typedef ::IceProxy::Ice::Object _Base;
        return dynamic_cast<SlaeSolverIce*>(_Base::ice_batchOneway().get());
    #else
        return dynamic_cast<SlaeSolverIce*>(::IceProxy::Ice::Object::ice_batchOneway().get());
    #endif
    }
    
    ::IceInternal::ProxyHandle<SlaeSolverIce> ice_datagram() const
    {
    #if defined(_MSC_VER) && (_MSC_VER < 1300) // VC++ 6 compiler bug
        typedef ::IceProxy::Ice::Object _Base;
        return dynamic_cast<SlaeSolverIce*>(_Base::ice_datagram().get());
    #else
        return dynamic_cast<SlaeSolverIce*>(::IceProxy::Ice::Object::ice_datagram().get());
    #endif
    }
    
    ::IceInternal::ProxyHandle<SlaeSolverIce> ice_batchDatagram() const
    {
    #if defined(_MSC_VER) && (_MSC_VER < 1300) // VC++ 6 compiler bug
        typedef ::IceProxy::Ice::Object _Base;
        return dynamic_cast<SlaeSolverIce*>(_Base::ice_batchDatagram().get());
    #else
        return dynamic_cast<SlaeSolverIce*>(::IceProxy::Ice::Object::ice_batchDatagram().get());
    #endif
    }
    
    ::IceInternal::ProxyHandle<SlaeSolverIce> ice_compress(bool __compress) const
    {
    #if defined(_MSC_VER) && (_MSC_VER < 1300) // VC++ 6 compiler bug
        typedef ::IceProxy::Ice::Object _Base;
        return dynamic_cast<SlaeSolverIce*>(_Base::ice_compress(__compress).get());
    #else
        return dynamic_cast<SlaeSolverIce*>(::IceProxy::Ice::Object::ice_compress(__compress).get());
    #endif
    }
    
    ::IceInternal::ProxyHandle<SlaeSolverIce> ice_timeout(int __timeout) const
    {
    #if defined(_MSC_VER) && (_MSC_VER < 1300) // VC++ 6 compiler bug
        typedef ::IceProxy::Ice::Object _Base;
        return dynamic_cast<SlaeSolverIce*>(_Base::ice_timeout(__timeout).get());
    #else
        return dynamic_cast<SlaeSolverIce*>(::IceProxy::Ice::Object::ice_timeout(__timeout).get());
    #endif
    }
    
    ::IceInternal::ProxyHandle<SlaeSolverIce> ice_connectionId(const std::string& __id) const
    {
    #if defined(_MSC_VER) && (_MSC_VER < 1300) // VC++ 6 compiler bug
        typedef ::IceProxy::Ice::Object _Base;
        return dynamic_cast<SlaeSolverIce*>(_Base::ice_connectionId(__id).get());
    #else
        return dynamic_cast<SlaeSolverIce*>(::IceProxy::Ice::Object::ice_connectionId(__id).get());
    #endif
    }
    
    static const ::std::string& ice_staticId();

private: 

    virtual ::IceInternal::Handle< ::IceDelegateM::Ice::Object> __createDelegateM();
    virtual ::IceInternal::Handle< ::IceDelegateD::Ice::Object> __createDelegateD();
    virtual ::IceProxy::Ice::Object* __newInstance() const;
};

}

}

namespace IceDelegate
{

namespace Enisey
{

class SlaeSolverIce : virtual public ::IceDelegate::Ice::Object
{
public:

    virtual void Solve(const ::Enisey::IntSequence&, const ::Enisey::DoubleSequence&, const ::Enisey::DoubleSequence&, ::Enisey::DoubleSequence&, const ::Ice::Context*) = 0;
};

}

}

namespace IceDelegateM
{

namespace Enisey
{

class SlaeSolverIce : virtual public ::IceDelegate::Enisey::SlaeSolverIce,
                      virtual public ::IceDelegateM::Ice::Object
{
public:

    virtual void Solve(const ::Enisey::IntSequence&, const ::Enisey::DoubleSequence&, const ::Enisey::DoubleSequence&, ::Enisey::DoubleSequence&, const ::Ice::Context*);
};

}

}

namespace IceDelegateD
{

namespace Enisey
{

class SlaeSolverIce : virtual public ::IceDelegate::Enisey::SlaeSolverIce,
                      virtual public ::IceDelegateD::Ice::Object
{
public:

    virtual void Solve(const ::Enisey::IntSequence&, const ::Enisey::DoubleSequence&, const ::Enisey::DoubleSequence&, ::Enisey::DoubleSequence&, const ::Ice::Context*);
};

}

}

namespace Enisey
{

class SlaeSolverIce : virtual public ::Ice::Object
{
public:

    typedef SlaeSolverIcePrx ProxyType;
    typedef SlaeSolverIcePtr PointerType;
    
    virtual ::Ice::ObjectPtr ice_clone() const;

    virtual bool ice_isA(const ::std::string&, const ::Ice::Current& = ::Ice::Current()) const;
    virtual ::std::vector< ::std::string> ice_ids(const ::Ice::Current& = ::Ice::Current()) const;
    virtual const ::std::string& ice_id(const ::Ice::Current& = ::Ice::Current()) const;
    static const ::std::string& ice_staticId();

    virtual void Solve(const ::Enisey::IntSequence&, const ::Enisey::DoubleSequence&, const ::Enisey::DoubleSequence&, ::Enisey::DoubleSequence&, const ::Ice::Current& = ::Ice::Current()) = 0;
    ::Ice::DispatchStatus ___Solve(::IceInternal::Incoming&, const ::Ice::Current&);

    virtual ::Ice::DispatchStatus __dispatch(::IceInternal::Incoming&, const ::Ice::Current&);

    virtual void __write(::IceInternal::BasicStream*) const;
    virtual void __read(::IceInternal::BasicStream*, bool);
// COMPILERFIX: Stream API is not supported with VC++ 6
#if !defined(_MSC_VER) || (_MSC_VER >= 1300)
    virtual void __write(const ::Ice::OutputStreamPtr&) const;
    virtual void __read(const ::Ice::InputStreamPtr&, bool);
#endif
};

inline bool operator==(const SlaeSolverIce& l, const SlaeSolverIce& r)
{
    return static_cast<const ::Ice::Object&>(l) == static_cast<const ::Ice::Object&>(r);
}

inline bool operator<(const SlaeSolverIce& l, const SlaeSolverIce& r)
{
    return static_cast<const ::Ice::Object&>(l) < static_cast<const ::Ice::Object&>(r);
}

}

namespace Enisey
{

template<class T>
class CallbackNC_SlaeSolverIce_Solve : public Callback_SlaeSolverIce_Solve_Base, public ::IceInternal::TwowayCallbackNC<T>
{
public:

    typedef IceUtil::Handle<T> TPtr;

    typedef void (T::*Exception)(const ::Ice::Exception&);
    typedef void (T::*Sent)(bool);
    typedef void (T::*Response)(const ::Enisey::DoubleSequence&);

    CallbackNC_SlaeSolverIce_Solve(const TPtr& obj, Response cb, Exception excb, Sent sentcb)
        : ::IceInternal::TwowayCallbackNC<T>(obj, cb != 0, excb, sentcb), response(cb)
    {
    }

    virtual void __completed(const ::Ice::AsyncResultPtr& __result) const
    {
        ::Enisey::SlaeSolverIcePrx __proxy = ::Enisey::SlaeSolverIcePrx::uncheckedCast(__result->getProxy());
        ::Enisey::DoubleSequence X;
        try
        {
            __proxy->end_Solve(X, __result);
        }
        catch(::Ice::Exception& ex)
        {
#if defined(_MSC_VER) && (_MSC_VER < 1300) // VC++ 6 compiler bug
            __exception(__result, ex);
#else
            ::IceInternal::CallbackNC<T>::__exception(__result, ex);
#endif
            return;
        }
        if(response)
        {
#if defined(_MSC_VER) && (_MSC_VER < 1300) // VC++ 6 compiler bug
            (callback.get()->*response)(X);
#else
            (::IceInternal::CallbackNC<T>::callback.get()->*response)(X);
#endif
        }
    }

    Response response;
};

template<class T> Callback_SlaeSolverIce_SolvePtr
newCallback_SlaeSolverIce_Solve(const IceUtil::Handle<T>& instance, void (T::*cb)(const ::Enisey::DoubleSequence&), void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_SlaeSolverIce_Solve<T>(instance, cb, excb, sentcb);
}

template<class T> Callback_SlaeSolverIce_SolvePtr
newCallback_SlaeSolverIce_Solve(T* instance, void (T::*cb)(const ::Enisey::DoubleSequence&), void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_SlaeSolverIce_Solve<T>(instance, cb, excb, sentcb);
}

template<class T, typename CT>
class Callback_SlaeSolverIce_Solve : public Callback_SlaeSolverIce_Solve_Base, public ::IceInternal::TwowayCallback<T, CT>
{
public:

    typedef IceUtil::Handle<T> TPtr;

    typedef void (T::*Exception)(const ::Ice::Exception& , const CT&);
    typedef void (T::*Sent)(bool , const CT&);
    typedef void (T::*Response)(const ::Enisey::DoubleSequence&, const CT&);

    Callback_SlaeSolverIce_Solve(const TPtr& obj, Response cb, Exception excb, Sent sentcb)
        : ::IceInternal::TwowayCallback<T, CT>(obj, cb != 0, excb, sentcb), response(cb)
    {
    }

    virtual void __completed(const ::Ice::AsyncResultPtr& __result) const
    {
        ::Enisey::SlaeSolverIcePrx __proxy = ::Enisey::SlaeSolverIcePrx::uncheckedCast(__result->getProxy());
        ::Enisey::DoubleSequence X;
        try
        {
            __proxy->end_Solve(X, __result);
        }
        catch(::Ice::Exception& ex)
        {
#if defined(_MSC_VER) && (_MSC_VER < 1300) // VC++ 6 compiler bug
            __exception(__result, ex);
#else
            ::IceInternal::Callback<T, CT>::__exception(__result, ex);
#endif
            return;
        }
        if(response)
        {
#if defined(_MSC_VER) && (_MSC_VER < 1300) // VC++ 6 compiler bug
            (callback.get()->*response)(X, CT::dynamicCast(__result->getCookie()));
#else
            (::IceInternal::Callback<T, CT>::callback.get()->*response)(X, CT::dynamicCast(__result->getCookie()));
#endif
        }
    }

    Response response;
};

template<class T, typename CT> Callback_SlaeSolverIce_SolvePtr
newCallback_SlaeSolverIce_Solve(const IceUtil::Handle<T>& instance, void (T::*cb)(const ::Enisey::DoubleSequence&, const CT&), void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_SlaeSolverIce_Solve<T, CT>(instance, cb, excb, sentcb);
}

template<class T, typename CT> Callback_SlaeSolverIce_SolvePtr
newCallback_SlaeSolverIce_Solve(T* instance, void (T::*cb)(const ::Enisey::DoubleSequence&, const CT&), void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_SlaeSolverIce_Solve<T, CT>(instance, cb, excb, sentcb);
}

}

#endif
